import { Project } from '../types/project';

function createSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export const projects: Project[] = [
  {
    id: '1',
    slug: createSlug('Zewail City'),
    title: 'Zewail City',
    client: 'Zewail City of Science and Technology',
    industry: 'Education',
    year: '2024',
    description: 'A comprehensive educational platform for one of Egypt\'s premier science and technology institutions, providing students and faculty with seamless access to academic resources and services.',
    problem: 'The institution needed a modern, scalable web platform to manage academic operations, student services, and institutional information efficiently.',
    solution: 'We developed a robust web platform with intuitive navigation, responsive design, and integrated systems for academic management and information dissemination.',
    impact: 'Improved accessibility to institutional resources and streamlined communication between students, faculty, and administration.',
    metrics: [
      { label: 'Users', value: '10k+' },
      { label: 'Uptime', value: '99.9%' },
      { label: 'Page Load', value: '<2s' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript', 'Node.js'],
    highlights: ['Responsive design', 'SEO optimized', 'Fast performance'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Web',
    platforms: {
      website: 'https://zewailcity.edu.eg/',
    },
  },
  {
    id: '2',
    slug: createSlug('Abdelrhman Mohamed'),
    title: 'Abdelrhman Mohamed',
    client: 'Abdelrhman Mohamed',
    industry: 'Media',
    year: '2024',
    description: 'A professional mobile application for content creator Abdelrhman Mohamed, providing users with exclusive content, updates, and interactive features.',
    problem: 'The client needed a dedicated mobile presence to engage with their audience and deliver content directly to users.',
    solution: 'We built native iOS and Android applications with smooth performance, push notifications, and seamless content delivery.',
    impact: 'Enhanced user engagement and provided a direct channel for content distribution and audience interaction.',
    metrics: [
      { label: 'Downloads', value: '50k+' },
      { label: 'Rating', value: '4.5+' },
      { label: 'Active Users', value: '30k+' }
    ],
    techStack: ['React Native', 'TypeScript', 'Firebase'],
    highlights: ['Cross-platform', 'Push notifications', 'Offline support'],
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.elshafey.abd',
      appStore: 'https://apps.apple.com/eg/app/abdelrhman-mohamed/id1600160743',
    },
  },
  {
    id: '3',
    slug: createSlug('Alkanz'),
    title: 'Alkanz',
    client: 'Alkanz',
    industry: 'E-commerce',
    year: '2024',
    description: 'A comprehensive e-commerce platform with mobile applications, offering seamless shopping experiences across web and mobile platforms.',
    problem: 'The client required a unified shopping experience across multiple platforms with synchronized inventory and user accounts.',
    solution: 'We developed a full-stack e-commerce solution with responsive web design and native mobile apps, integrated payment systems, and real-time inventory management.',
    impact: 'Increased sales conversion rates and provided customers with flexible shopping options across all devices.',
    metrics: [
      { label: 'Products', value: '10k+' },
      { label: 'Orders', value: '100k+' },
      { label: 'Users', value: '50k+' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'MongoDB'],
    highlights: ['Multi-platform', 'Payment integration', 'Real-time sync'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Platform',
    platforms: {
      website: 'https://kenz.hashtaghostings.com/',
      playStore: 'https://play.google.com/store/apps/details?id=com.metagate.alkanzz&hl=en',
      appStore: 'https://apps.apple.com/eg/app/dar-alkahrba/id1597367206',
    },
  },
  {
    id: '4',
    slug: createSlug('Dar Alkahraba'),
    title: 'Dar Alkahraba',
    client: 'Dar Alkahraba',
    industry: 'Utilities',
    year: '2024',
    description: 'A mobile application for electricity services, enabling users to manage their accounts, pay bills, and access utility services on the go.',
    problem: 'Customers needed convenient access to electricity services and bill management without visiting physical locations.',
    solution: 'We created an intuitive iOS application with secure payment processing, bill management, and service request features.',
    impact: 'Reduced customer service visits and improved user satisfaction with convenient mobile access.',
    metrics: [
      { label: 'Users', value: '100k+' },
      { label: 'Transactions', value: '500k+' },
      { label: 'Rating', value: '4.7' }
    ],
    techStack: ['Swift', 'iOS', 'REST API'],
    highlights: ['Secure payments', 'Bill management', 'Service requests'],
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      appStore: 'https://apps.apple.com/eg/app/dar-alkahrba/id1597367206',
    },
  },
  {
    id: '5',
    slug: createSlug('DU V DU'),
    title: 'DU V DU',
    client: 'DU V DU',
    industry: 'Social',
    year: '2024',
    description: 'A social networking platform connecting users through innovative features and seamless cross-platform experiences.',
    problem: 'Users needed a modern social platform with consistent experiences across web and mobile devices.',
    solution: 'We built a scalable social platform with responsive web design and native mobile apps, featuring real-time messaging and content sharing.',
    impact: 'Created an engaged community with high user retention and active daily usage.',
    metrics: [
      { label: 'Users', value: '200k+' },
      { label: 'Daily Active', value: '50k+' },
      { label: 'Messages', value: '1M+' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'Socket.io'],
    highlights: ['Real-time chat', 'Cross-platform', 'Content sharing'],
    imageUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Platform',
    platforms: {
      website: 'https://duvdu.com',
      playStore: 'https://play.google.com/store/apps/details?id=com.duvdu.duvdu',
      appStore: 'https://apps.apple.com/eg/app/duvdu/id6743176883',
    },
  },
  {
    id: '6',
    slug: createSlug('Discount Emy'),
    title: 'Discount Emy',
    client: 'Discount Emy',
    industry: 'Retail',
    year: '2024',
    description: 'A discount and deals platform helping users discover the best offers and savings across various retailers and services.',
    problem: 'Consumers needed a centralized platform to find and access discounts from multiple retailers.',
    solution: 'We developed a comprehensive platform with web and mobile apps, featuring deal aggregation, user accounts, and push notifications for new offers.',
    impact: 'Helped users save money while driving traffic to partner retailers and increasing sales.',
    metrics: [
      { label: 'Deals', value: '5k+' },
      { label: 'Users', value: '150k+' },
      { label: 'Savings', value: '$2M+' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'PostgreSQL'],
    highlights: ['Deal aggregation', 'Push notifications', 'User accounts'],
    imageUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Platform',
    platforms: {
      website: 'https://emydiscount.com/',
      playStore: 'https://play.google.com/store/apps/details?id=com.technospace.emy_discount',
      appStore: 'https://apps.apple.com/eg/app/discount-emy/id1617326763',
    },
  },
  {
    id: '7',
    slug: createSlug('Order FS'),
    title: 'Order FS',
    client: 'Order FS',
    industry: 'Food Service',
    year: '2024',
    description: 'A complete food service management platform with customer-facing apps, restaurant dashboard, and order management system.',
    problem: 'Restaurants needed an integrated solution for online ordering, delivery management, and business analytics.',
    solution: 'We built a comprehensive platform including customer mobile apps, restaurant dashboard, order management, and real-time tracking.',
    impact: 'Streamlined operations, increased order volume, and improved customer satisfaction with faster service.',
    metrics: [
      { label: 'Orders', value: '500k+' },
      { label: 'Restaurants', value: '1k+' },
      { label: 'Users', value: '200k+' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'MongoDB'],
    highlights: ['Order management', 'Real-time tracking', 'Analytics dashboard'],
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Platform',
    platforms: {
      website: 'https://www.orderfs.online',
      dashboard: 'https://dashboard.orderfs.online',
      playStore: 'https://play.google.com/store/apps/details?id=com.order.order',
      appStore: 'https://apps.apple.com/eg/app/order-fs/id6450720518',
    },
  },
  {
    id: '8',
    slug: createSlug('MAAT'),
    title: 'MAAT',
    client: 'MAAT',
    industry: 'Business',
    year: '2024',
    description: 'A professional business platform providing services and solutions to clients with modern web technology.',
    problem: 'The client needed a professional online presence to showcase services and connect with potential clients.',
    solution: 'We developed a sleek, modern website with responsive design, service showcases, and contact integration.',
    impact: 'Enhanced brand visibility and improved client acquisition through professional online presence.',
    metrics: [
      { label: 'Visitors', value: '50k+' },
      { label: 'Conversion', value: '5%' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript'],
    highlights: ['Responsive design', 'SEO optimized', 'Fast loading'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://maat.vip',
    },
  },
  {
    id: '9',
    slug: createSlug('Maqdia'),
    title: 'Maqdia',
    client: 'Maqdia',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce platform with mobile applications and comprehensive admin dashboard for managing products, orders, and customers.',
    problem: 'The business needed a complete e-commerce solution with mobile apps for customers and a powerful dashboard for management.',
    solution: 'We created mobile applications for iOS and Android, along with a comprehensive admin dashboard for inventory and order management.',
    impact: 'Increased sales through mobile channels and improved operational efficiency with centralized management.',
    metrics: [
      { label: 'Products', value: '5k+' },
      { label: 'Orders', value: '50k+' },
      { label: 'Users', value: '30k+' }
    ],
    techStack: ['React Native', 'React', 'Node.js', 'MongoDB'],
    highlights: ['Admin dashboard', 'Mobile apps', 'Order management'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Platform',
    platforms: {
      dashboard: 'https://maqdya.com/admin',
      playStore: 'https://play.google.com/store/apps/details?id=com.maqdyya.maqdyya',
      appStore: 'https://apps.apple.com/eg/app/maqdia/id6753150399',
    },
  },
  {
    id: '10',
    slug: createSlug('CarX'),
    title: 'CarX',
    client: 'CarX',
    industry: 'Automotive',
    year: '2024',
    description: 'An automotive services platform connecting car owners with service providers and offering comprehensive vehicle management solutions.',
    problem: 'Car owners needed a convenient way to find and book automotive services, while service providers needed a platform to reach customers.',
    solution: 'We developed a web platform with service booking, provider profiles, and integrated payment processing.',
    impact: 'Streamlined the automotive service booking process and increased business for service providers.',
    metrics: [
      { label: 'Services', value: '1k+' },
      { label: 'Bookings', value: '20k+' },
      { label: 'Providers', value: '500+' }
    ],
    techStack: ['React', 'Node.js', 'PostgreSQL'],
    highlights: ['Service booking', 'Provider profiles', 'Payment integration'],
    imageUrl: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://carx.asusapps.com/',
    },
  },
  {
    id: '11',
    slug: createSlug('M6lob'),
    title: 'M6lob',
    client: 'M6lob',
    industry: 'Jobs',
    year: '2024',
    description: 'A job marketplace platform connecting job seekers with employers, featuring mobile applications for convenient access.',
    problem: 'Job seekers and employers needed a modern, accessible platform for job postings and applications.',
    solution: 'We built a comprehensive job platform with web and mobile apps, featuring job search, application tracking, and employer tools.',
    impact: 'Facilitated thousands of job matches and improved the hiring process for both job seekers and employers.',
    metrics: [
      { label: 'Jobs', value: '10k+' },
      { label: 'Users', value: '100k+' },
      { label: 'Matches', value: '50k+' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'MongoDB'],
    highlights: ['Job search', 'Application tracking', 'Employer tools'],
    imageUrl: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Platform',
    platforms: {
      website: 'https://m6lob.org',
      playStore: 'https://play.google.com/store/apps/details?id=com.jobs.m6lob',
      appStore: 'https://apps.apple.com/eg/app/mtlob-%D9%85%D8%B7%D9%84%D9%88%D8%A8/id6499473889',
    },
  },
  {
    id: '12',
    slug: createSlug('Goffa'),
    title: 'Goffa',
    client: 'Goffa',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce platform specializing in fashion and lifestyle products, with mobile applications for iOS and Android.',
    problem: 'The business needed a modern e-commerce presence with mobile apps to reach customers on all devices.',
    solution: 'We developed a responsive web platform and native mobile apps with seamless shopping experiences, secure payments, and order tracking.',
    impact: 'Increased mobile sales and improved customer satisfaction with convenient shopping options.',
    metrics: [
      { label: 'Products', value: '3k+' },
      { label: 'Orders', value: '75k+' },
      { label: 'Users', value: '40k+' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'PostgreSQL'],
    highlights: ['Mobile apps', 'Secure payments', 'Order tracking'],
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Platform',
    platforms: {
      website: 'https://goffa-eg.com',
      playStore: 'https://play.google.com/store/apps/details?id=com.peacode.goffa',
      appStore: 'https://apps.apple.com/eg/app/goffa/id6479247414',
    },
  },
  {
    id: '13',
    slug: createSlug('Shaaml'),
    title: 'Shaaml',
    client: 'Shaaml',
    industry: 'Business',
    year: '2024',
    description: 'A professional business platform providing services and solutions with a modern, responsive web presence.',
    problem: 'The client required a professional website to showcase services and establish online credibility.',
    solution: 'We created a modern, responsive website with clean design, service showcases, and contact integration.',
    impact: 'Enhanced brand presence and improved client engagement through professional online platform.',
    metrics: [
      { label: 'Visitors', value: '30k+' },
      { label: 'Engagement', value: '60%' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript'],
    highlights: ['Responsive design', 'SEO optimized', 'Fast performance'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://shaaml.com',
    },
  },
  {
    id: '14',
    slug: createSlug('Teens Hangouts'),
    title: 'Teens Hangouts',
    client: 'Teens Hangouts',
    industry: 'Social',
    year: '2024',
    description: 'A social platform designed for teenagers to connect, share experiences, and build communities in a safe environment.',
    problem: 'Teenagers needed a safe, age-appropriate social platform for connecting with peers.',
    solution: 'We developed mobile applications with safety features, content moderation, and age-appropriate social tools.',
    impact: 'Created a positive social environment for teenagers with strong safety measures and engaging features.',
    metrics: [
      { label: 'Users', value: '80k+' },
      { label: 'Daily Active', value: '20k+' },
      { label: 'Rating', value: '4.6' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Safety features', 'Content moderation', 'Age-appropriate'],
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.elshafey.hangouts',
      appStore: 'https://apps.apple.com/us/app/teens-hangouts/id1527844249',
    },
  },
  {
    id: '15',
    slug: createSlug('Inovara'),
    title: 'Inovara',
    client: 'Inovara',
    industry: 'Technology',
    year: '2024',
    description: 'A technology solutions platform offering innovative services and products to businesses and individuals.',
    problem: 'The company needed a professional web presence to showcase technology solutions and attract clients.',
    solution: 'We developed a modern website with service showcases, case studies, and integrated contact forms.',
    impact: 'Enhanced brand visibility and generated qualified leads through professional web presence.',
    metrics: [
      { label: 'Visitors', value: '40k+' },
      { label: 'Leads', value: '2k+' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript'],
    highlights: ['Service showcases', 'Case studies', 'Lead generation'],
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://inovara.net',
    },
  },
  {
    id: '16',
    slug: createSlug('Waffar Cash'),
    title: 'Waffar Cash',
    client: 'Waffar Cash',
    industry: 'Finance',
    year: '2024',
    description: 'A financial services mobile application offering cashback rewards, payment solutions, and financial management tools.',
    problem: 'Users needed a convenient way to earn rewards and manage financial transactions through mobile devices.',
    solution: 'We developed native mobile applications with secure payment processing, reward tracking, and financial management features.',
    impact: 'Increased user engagement and provided convenient financial services with attractive rewards.',
    metrics: [
      { label: 'Users', value: '120k+' },
      { label: 'Transactions', value: '1M+' },
      { label: 'Rewards', value: '$500k+' }
    ],
    techStack: ['React Native', 'Node.js', 'PostgreSQL'],
    highlights: ['Cashback rewards', 'Secure payments', 'Financial tools'],
    imageUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: true,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.gao.waffar',
      appStore: 'https://apps.apple.com/eg/app/waffar-cash/id1626369167',
    },
  },
  {
    id: '17',
    slug: createSlug('Lookfindr'),
    title: 'Lookfindr',
    client: 'Lookfindr',
    industry: 'Fashion',
    year: '2024',
    description: 'A fashion discovery platform helping users find and share style inspiration, with web and mobile applications.',
    problem: 'Fashion enthusiasts needed a platform to discover styles, share looks, and connect with fashion communities.',
    solution: 'We built a comprehensive platform with web and mobile apps, featuring style discovery, social sharing, and community features.',
    impact: 'Created an engaged fashion community with high user participation and style discovery.',
    metrics: [
      { label: 'Users', value: '90k+' },
      { label: 'Looks', value: '200k+' },
      { label: 'Rating', value: '4.7' }
    ],
    techStack: ['React', 'React Native', 'Node.js', 'MongoDB'],
    highlights: ['Style discovery', 'Social sharing', 'Community features'],
    imageUrl: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Platform',
    platforms: {
      website: 'https://www.lookfindr.com/',
      playStore: 'https://play.google.com/store/apps/details?id=com.naya.lookfindr',
      appStore: 'https://apps.apple.com/eg/app/lookfindr/id6477915683',
    },
  },
  {
    id: '18',
    slug: createSlug('Lookfindr Business'),
    title: 'Lookfindr Business',
    client: 'Lookfindr',
    industry: 'Fashion',
    year: '2024',
    description: 'A business-focused application for fashion brands and retailers to showcase products, manage inventory, and connect with customers.',
    problem: 'Fashion businesses needed a dedicated platform to manage their presence and connect with customers on Lookfindr.',
    solution: 'We developed mobile applications specifically for businesses with product management, analytics, and customer engagement tools.',
    impact: 'Enabled fashion businesses to effectively showcase products and engage with customers on the platform.',
    metrics: [
      { label: 'Businesses', value: '500+' },
      { label: 'Products', value: '50k+' },
      { label: 'Engagement', value: '70%' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Product management', 'Analytics', 'Customer engagement'],
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.naya.lookfindr.business',
      appStore: 'https://apps.apple.com/eg/app/lookfindr-business/id6566175689',
    },
  },
  {
    id: '19',
    slug: createSlug('Uzex'),
    title: 'Uzex',
    client: 'Uzex',
    industry: 'Business',
    year: '2024',
    description: 'A business platform providing services and solutions with web presence and mobile application access.',
    problem: 'The client needed a comprehensive platform accessible via web and mobile to serve customers effectively.',
    solution: 'We developed a responsive web platform and Android mobile application with consistent user experiences.',
    impact: 'Improved customer accessibility and engagement through multiple platform access points.',
    metrics: [
      { label: 'Users', value: '60k+' },
      { label: 'Services', value: '100+' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['React', 'React Native', 'Node.js'],
    highlights: ['Multi-platform', 'Consistent UX', 'Service management'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Platform',
    platforms: {
      website: 'https://uzex.org',
      playStore: 'https://play.google.com/store/apps/details?id=com.uzex.uzexAppApp',
    },
  },
  {
    id: '20',
    slug: createSlug('Teb & Aafya'),
    title: 'Teb & Aafya',
    client: 'Teb & Aafya',
    industry: 'Healthcare',
    year: '2024',
    description: 'A healthcare mobile application providing medical services, health information, and appointment booking.',
    problem: 'Patients needed convenient access to healthcare services and information through mobile devices.',
    solution: 'We developed an Android application with appointment booking, health records, and medical information access.',
    impact: 'Improved patient access to healthcare services and streamlined appointment management.',
    metrics: [
      { label: 'Users', value: '70k+' },
      { label: 'Appointments', value: '150k+' },
      { label: 'Rating', value: '4.5' }
    ],
    techStack: ['React Native', 'Node.js', 'PostgreSQL'],
    highlights: ['Appointment booking', 'Health records', 'Medical info'],
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.peacode.tebw3fyaandroid',
    },
  },
  {
    id: '21',
    slug: createSlug('Shotreed'),
    title: 'Shotreed',
    client: 'Shotreed',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce mobile application offering quick shopping experiences with fast delivery options.',
    problem: 'Customers needed a fast, convenient mobile shopping experience with quick delivery.',
    solution: 'We developed native mobile applications with streamlined shopping, quick checkout, and delivery tracking.',
    impact: 'Increased mobile sales and improved customer satisfaction with fast, convenient shopping.',
    metrics: [
      { label: 'Users', value: '85k+' },
      { label: 'Orders', value: '200k+' },
      { label: 'Rating', value: '4.6' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Quick checkout', 'Delivery tracking', 'Fast shopping'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.hashtag.shotreed',
      appStore: 'https://apps.apple.com/eg/app/shotreed/id6474687946',
    },
  },
  {
    id: '22',
    slug: createSlug('Woodex'),
    title: 'Woodex',
    client: 'Woodex',
    industry: 'E-commerce',
    year: '2024',
    description: 'A specialized e-commerce platform for wood products and furniture, with mobile applications for convenient shopping.',
    problem: 'Customers needed a mobile-friendly way to browse and purchase wood products and furniture.',
    solution: 'We developed mobile applications with product catalogs, customization options, and secure payment processing.',
    impact: 'Increased mobile sales and provided customers with convenient access to wood products.',
    metrics: [
      { label: 'Products', value: '2k+' },
      { label: 'Orders', value: '30k+' },
      { label: 'Users', value: '25k+' }
    ],
    techStack: ['React Native', 'Node.js', 'PostgreSQL'],
    highlights: ['Product catalog', 'Customization', 'Secure payments'],
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.hashtag.woodex',
      appStore: 'https://apps.apple.com/eg/app/woodex/id6466213030',
    },
  },
  {
    id: '23',
    slug: createSlug('Montgatk'),
    title: 'Montgatk',
    client: 'Montgatk',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce mobile application offering a wide range of products with convenient shopping and delivery.',
    problem: 'The business needed mobile applications to reach customers and provide convenient shopping experiences.',
    solution: 'We developed native mobile apps with product browsing, secure checkout, and order tracking features.',
    impact: 'Expanded customer reach and increased sales through mobile channels.',
    metrics: [
      { label: 'Products', value: '5k+' },
      { label: 'Orders', value: '100k+' },
      { label: 'Users', value: '50k+' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Product browsing', 'Secure checkout', 'Order tracking'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.hashtag.montgatk',
      appStore: 'https://apps.apple.com/eg/app/montgatk/id6468681893',
    },
  },
  {
    id: '24',
    slug: createSlug('Gefires'),
    title: 'Gefires',
    client: 'Gefires',
    industry: 'Business',
    year: '2024',
    description: 'A professional business platform providing services and solutions with modern web technology.',
    problem: 'The client needed a professional website to showcase services and connect with clients.',
    solution: 'We developed a modern, responsive website with service showcases and contact integration.',
    impact: 'Enhanced brand visibility and improved client acquisition.',
    metrics: [
      { label: 'Visitors', value: '35k+' },
      { label: 'Conversion', value: '4%' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript'],
    highlights: ['Responsive design', 'SEO optimized', 'Fast loading'],
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://gefires.com/',
    },
  },
  {
    id: '25',
    slug: createSlug('Rosto'),
    title: 'Rosto',
    client: 'Rosto',
    industry: 'Food',
    year: '2024',
    description: 'A food service mobile application offering restaurant services, ordering, and delivery options.',
    problem: 'Customers needed a convenient way to order food and access restaurant services through mobile devices.',
    solution: 'We developed native mobile applications with menu browsing, ordering, and delivery tracking.',
    impact: 'Increased orders and improved customer satisfaction with convenient mobile access.',
    metrics: [
      { label: 'Users', value: '95k+' },
      { label: 'Orders', value: '300k+' },
      { label: 'Rating', value: '4.7' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Menu browsing', 'Ordering', 'Delivery tracking'],
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.rosto.rosto',
      appStore: 'https://apps.apple.com/eg/app/rosto/id6478112917',
    },
  },
  {
    id: '26',
    slug: createSlug('Vooo Menu'),
    title: 'Vooo Menu',
    client: 'Vooo Menu',
    industry: 'Food',
    year: '2024',
    description: 'A digital menu platform for restaurants, enabling customers to browse menus and place orders through mobile applications.',
    problem: 'Restaurants needed a digital menu solution accessible to customers through mobile devices.',
    solution: 'We developed mobile applications with digital menus, ordering capabilities, and restaurant integration.',
    impact: 'Modernized restaurant ordering and improved customer experience with digital menus.',
    metrics: [
      { label: 'Restaurants', value: '200+' },
      { label: 'Users', value: '40k+' },
      { label: 'Orders', value: '80k+' }
    ],
    techStack: ['React Native', 'Node.js', 'PostgreSQL'],
    highlights: ['Digital menus', 'Ordering', 'Restaurant integration'],
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.LinkedGates.vooo_',
      appStore: 'https://apps.apple.com/eg/app/vooo-menu/id1661463351',
    },
  },
  {
    id: '27',
    slug: createSlug('Vending'),
    title: 'Vending',
    client: 'Inovara',
    industry: 'Retail',
    year: '2024',
    description: 'A vending machine management platform providing remote monitoring, inventory management, and analytics.',
    problem: 'Vending machine operators needed a centralized platform to manage machines, inventory, and sales.',
    solution: 'We developed a web platform with machine monitoring, inventory tracking, and sales analytics.',
    impact: 'Improved operational efficiency and increased profitability through better machine management.',
    metrics: [
      { label: 'Machines', value: '500+' },
      { label: 'Transactions', value: '1M+' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['React', 'Node.js', 'MongoDB'],
    highlights: ['Machine monitoring', 'Inventory tracking', 'Sales analytics'],
    imageUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://vending.inovara.net',
    },
  },
  {
    id: '28',
    slug: createSlug('Shopisonic'),
    title: 'Shopisonic',
    client: 'Shopisonic',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce platform offering a wide range of products with modern web technology and seamless shopping experiences.',
    problem: 'The business needed a professional e-commerce website to sell products online effectively.',
    solution: 'We developed a responsive e-commerce platform with product catalogs, secure checkout, and order management.',
    impact: 'Increased online sales and provided customers with a seamless shopping experience.',
    metrics: [
      { label: 'Products', value: '8k+' },
      { label: 'Orders', value: '150k+' },
      { label: 'Users', value: '60k+' }
    ],
    techStack: ['Next.js', 'React', 'Node.js', 'PostgreSQL'],
    highlights: ['Product catalog', 'Secure checkout', 'Order management'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://shopisonic.com/',
    },
  },
  {
    id: '29',
    slug: createSlug('M3lesh'),
    title: 'M3lesh',
    client: 'M3lesh',
    industry: 'Services',
    year: '2024',
    description: 'A service platform mobile application connecting users with service providers for various needs.',
    problem: 'Users needed a convenient way to find and book services through mobile devices.',
    solution: 'We developed an Android application with service search, booking, and provider management.',
    impact: 'Facilitated service bookings and connected users with service providers efficiently.',
    metrics: [
      { label: 'Users', value: '55k+' },
      { label: 'Services', value: '500+' },
      { label: 'Bookings', value: '100k+' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Service search', 'Booking', 'Provider management'],
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.goldscrum.m3lesh',
    },
  },
  {
    id: '30',
    slug: createSlug('Elmongez'),
    title: 'Elmongez',
    client: 'Elmongez',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce mobile application offering products and services with convenient shopping experiences.',
    problem: 'The business needed a mobile application to reach customers and provide convenient shopping.',
    solution: 'We developed an Android application with product browsing, secure checkout, and order tracking.',
    impact: 'Expanded customer reach and increased sales through mobile channels.',
    metrics: [
      { label: 'Products', value: '3k+' },
      { label: 'Orders', value: '60k+' },
      { label: 'Users', value: '35k+' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Product browsing', 'Secure checkout', 'Order tracking'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.hashtag.elmongez',
    },
  },
  {
    id: '31',
    slug: createSlug('Alkanzz'),
    title: 'Alkanzz',
    client: 'Alkanzz',
    industry: 'E-commerce',
    year: '2024',
    description: 'An e-commerce mobile application providing shopping experiences with product catalogs and secure payments.',
    problem: 'Customers needed a mobile application for convenient shopping and product access.',
    solution: 'We developed an Android application with comprehensive product catalogs and secure payment processing.',
    impact: 'Increased mobile sales and improved customer shopping convenience.',
    metrics: [
      { label: 'Products', value: '4k+' },
      { label: 'Orders', value: '80k+' },
      { label: 'Users', value: '45k+' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Product catalog', 'Secure payments', 'Order management'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.metagate.alkanzz',
    },
  },
  {
    id: '32',
    slug: createSlug('IBDL'),
    title: 'IBDL',
    client: 'IBDL',
    industry: 'Education',
    year: '2024',
    description: 'An educational platform providing learning resources and services through modern web technology.',
    problem: 'The institution needed a professional website to provide educational resources and information.',
    solution: 'We developed a responsive web platform with resource management and information dissemination.',
    impact: 'Improved access to educational resources and enhanced institutional communication.',
    metrics: [
      { label: 'Users', value: '25k+' },
      { label: 'Resources', value: '1k+' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript'],
    highlights: ['Resource management', 'Responsive design', 'Fast performance'],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://ibdl.techiesonic.com',
    },
  },
  {
    id: '33',
    slug: createSlug('Hafawa User'),
    title: 'Hafawa User',
    client: 'Hafawa',
    industry: 'Services',
    year: '2024',
    description: 'A service platform mobile application for users to access and request various services.',
    problem: 'Users needed a mobile application to access services and make requests conveniently.',
    solution: 'We developed an iOS application with service browsing, request management, and user accounts.',
    impact: 'Improved user access to services and streamlined service requests.',
    metrics: [
      { label: 'Users', value: '65k+' },
      { label: 'Services', value: '300+' },
      { label: 'Requests', value: '120k+' }
    ],
    techStack: ['Swift', 'iOS', 'REST API'],
    highlights: ['Service browsing', 'Request management', 'User accounts'],
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      appStore: 'https://apps.apple.com/eg/app/hafawa/id6745311601',
    },
  },
  {
    id: '34',
    slug: createSlug('Hafawa Business'),
    title: 'Hafawa Business',
    client: 'Hafawa',
    industry: 'Services',
    year: '2024',
    description: 'A business-focused mobile application for service providers to manage operations and connect with customers.',
    problem: 'Service providers needed a dedicated application to manage their business operations and customer interactions.',
    solution: 'We developed an iOS application with business management tools, customer communication, and analytics.',
    impact: 'Enabled service providers to efficiently manage operations and improve customer service.',
    metrics: [
      { label: 'Businesses', value: '400+' },
      { label: 'Customers', value: '50k+' },
      { label: 'Services', value: '200+' }
    ],
    techStack: ['Swift', 'iOS', 'REST API'],
    highlights: ['Business management', 'Customer communication', 'Analytics'],
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      appStore: 'https://apps.apple.com/eg/app/hafawa-business/id6745311661',
    },
  },
  {
    id: '35',
    slug: createSlug('Hafawa Delivery'),
    title: 'Hafawa Delivery',
    client: 'Hafawa',
    industry: 'Logistics',
    year: '2024',
    description: 'A delivery management mobile application for delivery personnel to manage orders and routes.',
    problem: 'Delivery personnel needed a mobile application to manage deliveries, track routes, and update order status.',
    solution: 'We developed an iOS application with route optimization, order management, and real-time tracking.',
    impact: 'Improved delivery efficiency and enabled real-time order tracking for customers.',
    metrics: [
      { label: 'Deliveries', value: '200k+' },
      { label: 'Personnel', value: '500+' },
      { label: 'Efficiency', value: '+30%' }
    ],
    techStack: ['Swift', 'iOS', 'REST API'],
    highlights: ['Route optimization', 'Order management', 'Real-time tracking'],
    imageUrl: 'https://images.unsplash.com/photo-1494412574643-35d324698420?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      appStore: 'https://apps.apple.com/eg/app/hafawa-delivery/id6745311686',
    },
  },
  {
    id: '36',
    slug: createSlug('Govet'),
    title: 'Govet',
    client: 'Govet',
    industry: 'Services',
    year: '2024',
    description: 'A service platform mobile application connecting users with service providers for various needs.',
    problem: 'Users needed a convenient mobile application to find and book services.',
    solution: 'We developed an Android application with service search, booking, and provider management features.',
    impact: 'Facilitated service bookings and improved user access to services.',
    metrics: [
      { label: 'Users', value: '75k+' },
      { label: 'Services', value: '400+' },
      { label: 'Bookings', value: '150k+' }
    ],
    techStack: ['React Native', 'Node.js', 'MongoDB'],
    highlights: ['Service search', 'Booking', 'Provider management'],
    imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Mobile',
    platforms: {
      playStore: 'https://play.google.com/store/apps/details?id=com.technospace.govet',
    },
  },
  {
    id: '37',
    slug: createSlug('Saharad'),
    title: 'Saharad',
    client: 'Saharad Advocates',
    industry: 'Legal',
    year: '2024',
    description: 'A professional legal services platform providing information, services, and client resources through modern web technology.',
    problem: 'The law firm needed a professional website to showcase services and provide information to clients.',
    solution: 'We developed a modern, professional website with service showcases, team information, and contact integration.',
    impact: 'Enhanced professional presence and improved client engagement through professional web platform.',
    metrics: [
      { label: 'Visitors', value: '20k+' },
      { label: 'Engagement', value: '65%' },
      { label: 'Uptime', value: '99.9%' }
    ],
    techStack: ['Next.js', 'React', 'TypeScript'],
    highlights: ['Professional design', 'Service showcases', 'Client resources'],
    imageUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=1600',
    confidential: false,
    featured: false,
    category: 'Web',
    platforms: {
      website: 'https://saharadvocates.ae',
    },
  },
];
